### ISSUE TITLE
Failure to run

### ISSUE THREAD

**Issue by funnybananas** [wavvs/nanorobeus#2]
After compiling the 64bit BOF and running in Cobalt Strike, I receive the following error:

```
[-] no slot for function (reduce number of Win32 APIs called)
```

No errors in script console.

**Comment by D1sAbl4** [comment]
> no slot for function (reduce number of Win32 APIs called)

![image](https://user-images.githubusercontent.com/51101413/222037589-5c8f2548-1af8-45b7-9446-ab37118768e1.png)

**Comment by D1sAbl4** [comment]
> After compiling the 64bit BOF and running in Cobalt Strike, I receive the following error:
> 
> ```
> [-] no slot for function (reduce number of Win32 APIs called)
> ```
> 
> No errors in script console.

Exceeded the dynamic function call limit, the number before CS4.7 was 32

**Comment by funnybananas** [comment]
I'm currently testing this on CS 4.7.2. Apologize, I haven't encountered this before so was just unfamiliar with the error. Is this limit enforced per BOF? Does this mean there are more than 64 calls?

**Comment by D1sAbl4** [comment]
Yes, this error means that the win32 api called exceeded the maximum limit. Look carefully at the error message: `reduce number of Win32 APIs called`
```sh
[-] no slot for function (reduce number of Win32 APIs called)
```

**Comment by D1sAbl4** [comment]
Ways to avoid exceeding limits: Get exported functions from dll loaded in memory
### exmaple
```C
DECLSPEC_IMPORT FARPROC WINAPI KERNEL32$GetProcAddress(HANDLE, LPCSTR);
DECLSPEC_IMPORT HMODULE WINAPI KERNEL32$GetModuleHandleW(LPCWSTR);

#define GetModuleHandleW     KERNEL32$GetModuleHandleW
#define GetProcAddress     KERNEL32$GetProcAddress

typedef NTSTATUS(WINAPI* _RtlAdjustPrivilege)(
    ULONG Privilege, BOOL Enable,
    BOOL CurrentThread, PULONG Enabled
);

_RtlAdjustPrivilege RtlAdjustPrivilege = (_RtlAdjustPrivilege)GetProcAddress(GetModuleHandleW(L"ntdll.dll"), "RtlAdjustPrivilege");
```

**Comment by funnybananas** [comment]
Awesome, thanks for the nudge. I'll take a look and see if I can get it to run in CS.

**Comment by D1sAbl4** [comment]
Sorry, I forgot to define GetProcAddress and GetModuleHandleW, already patched

**Comment by funnybananas** [comment]
Using your example, I tried to patch some of the code to handle the exported functions loaded from a dll, I get the following error:

## Code
```c
DECLSPEC_IMPORT FARPROC WINAPI KERNEL32$GetProcAddress(HANDLE, LPCSTR);
DECLSPEC_IMPORT HMODULE WINAPI KERNEL32$GetModuleHandleW(LPCWSTR);

typedef HLOCAL(WINAPI* _LocalFree)(HLOCAL hMem);
_LocalFree MLocalFree = (_LocalFree)GetProcAddress(GetModuleHandleW(L"Kernel32.dll"), "LocalFree");
```

## Error
```c
_LocalFree MLocalFree = (_LocalFree)GetProcAddress(GetModuleHandleW(L"Kernel32.dll"), "LocalFree");
|                       ^
error: initializer element is not constant
```

**Comment by D1sAbl4** [comment]
https://gist.github.com/D1sAbl4/d4b04ca6b4036ef6b4acde8163a3e07f , I wrote a bof demo hope it will be useful to you
## Build
![image](https://user-images.githubusercontent.com/51101413/222300138-ba3d87fb-ae56-4e47-8263-d2458d229e2d.png)
## Execute
![image](https://user-images.githubusercontent.com/51101413/222300199-adfeece6-ebf6-49dc-95fa-13e1e9b4acbd.png)

**Comment by D1sAbl4** [comment]
https://gist.github.com/D1sAbl4/d4b04ca6b4036ef6b4acde8163a3e07f , I wrote a bof demo hope it will be useful to you
## Build
![image](https://user-images.githubusercontent.com/51101413/222300138-ba3d87fb-ae56-4e47-8263-d2458d229e2d.png)
## Execute
![image](https://user-images.githubusercontent.com/51101413/222300199-adfeece6-ebf6-49dc-95fa-13e1e9b4acbd.png)

**Comment by funnybananas** [comment]
That does help. My guess is it's because my initializer isn't inside a function. In your example, you've put it inside the `go` entry-point. Tomorrow I'll move it into one and test again. Thanks!

**Comment by wavvs** [comment]
@funnybananas Added support for the CS. Build using `make cs_bof`. Let me know if there are any issues.
