### ISSUE TITLE
Make issue

### ISSUE THREAD

**Issue by Cyb3rC3lt** [wavvs/nanorobeus#4]
Hi there,

I am getting a compilation as shown below. I see for others the gcc version was old but I think mine is okay. I am just cloning it and doing make. Any further tips please? Thanks

![image](https://github.com/wavvs/nanorobeus/assets/33097451/e8e0d241-b14e-4d07-bff6-6fec98f674e3)

![image](https://github.com/wavvs/nanorobeus/assets/33097451/861e31bc-8010-4776-8ada-2350a3fd00ec)

**Comment by wavvs** [comment]
If you don't need exe just run `make bof`. If you want to build exe on Kali revert to the previous commit.

**Comment by Cyb3rC3lt** [comment]
Perfect, make bof worked well and I just wanted a Sliver bof object file. Thank you
